name: elcm

model_type: segmented_discretechoice

segmentation_col: empsix

choosers_fit_filters: building_id != -1

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters:
- job_spaces > 0

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 5000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(non_residential_price) + np.log1p(stories) + office_1500 + industrial_1500
        + ave_sqft_per_unit + ave_lot_size_per_unit + ave_income + ave_hhsize
        + retail_1500 + jobs_45 + residential_units_1500 + residential_units_45 +
        ave_income_1500 + juris_ave_income + embarcadero + stanford

models:
    AGREMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -3095334.8899371065
            ratio: -0.11583326596408683
        name: AGREMPN
    FPSEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2981315.548124915
            ratio: -0.15850790824990324
        name: FPSEMPN
    HEREMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2971012.5955515252
            ratio: -0.16252541125627462
        name: HEREMPN
    MWTEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2914689.78815032
            ratio: -0.1849897898338475
        name: MWTEMPN
    OTHEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2985436.729154272
            ratio: -0.15690867127153574
        name: OTHEMPN
    RETEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2859053.844254013
            ratio: -0.20804917558042613
        name: RETEMPN

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
