name: elcm

model_type: segmented_discretechoice

segmentation_col: empsix

choosers_fit_filters: building_id != -1

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters:
- job_spaces > 0

interaction_predict_filters: null

choice_column: null

sample_size: 50

estimation_sample_size: 5000

prediction_sample_size: null

default_config:
    model_expression: np.log1p(non_residential_price) + office_1500 + industrial_1500
        + retail_1500 + jobs_45 + residential_units_1500 + residential_units_45 +
        ave_income_1500 + juris_ave_income + embarcadero + stanford

models:
    AGREMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -3115940.795083891
            ratio: -0.10845419301303494
        name: AGREMPN
    FPSEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -3008790.088320625
            ratio: -0.1479290804959119
        name: FPSEMPN
    HEREMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2951780.417414527
            ratio: -0.17009978761102085
        name: HEREMPN
    MWTEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2953841.007929206
            ratio: -0.16928352955342518
        name: MWTEMPN
    OTHEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -3043820.127070156
            ratio: -0.13471805011541726
        name: OTHEMPN
    RETEMPN:
        fit_parameters:
            Coefficient:
                ave_income_1500: 0.0
                embarcadero: 0.0
                industrial_1500: 0.0
                jobs_45: 0.0
                juris_ave_income: 0.0
                np.log1p(non_residential_price): .nan
                office_1500: 0.0
                residential_units_1500: 0.0
                residential_units_45: 0.0
                retail_1500: 0.0
                stanford: 0.0
            Std. Error:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
            T-Score:
                ave_income_1500: .nan
                embarcadero: .nan
                industrial_1500: .nan
                jobs_45: .nan
                juris_ave_income: .nan
                np.log1p(non_residential_price): .nan
                office_1500: .nan
                residential_units_1500: .nan
                residential_units_45: .nan
                retail_1500: .nan
                stanford: .nan
        fitted: true
        log_likelihoods:
            convergence: -3453877.6394911087
            'null': -2898891.9275377872
            ratio: -0.1914475343772839
        name: RETEMPN

fitted: true

choice_mode: aggregate

remove_alts: true

probability_mode: single_chooser
